/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppCoursesRouteImport } from './routes/_app.courses'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFeedRouteImport } from './routes/_app.feed'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRepRouteImport } from './routes/_app.rep'
import { Route as AppCoursesIndexRouteImport } from './routes/_app.courses.index'
import { Route as AppCoursesIdRouteImport } from './routes/_app.courses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRepRoute = AppRepRouteImport.update({
  id: '/rep',
  path: '/rep',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppCoursesIdRoute = AppCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/courses': typeof AppCoursesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRoute
  '/profile': typeof AppProfileRoute
  '/rep': typeof AppRepRoute
  '/courses/$id': typeof AppCoursesIdRoute
  '/courses/': typeof AppCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/feed': typeof AppFeedRoute
  '/profile': typeof AppProfileRoute
  '/rep': typeof AppRepRoute
  '/courses/$id': typeof AppCoursesIdRoute
  '/courses': typeof AppCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/courses': typeof AppCoursesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rep': typeof AppRepRoute
  '/_app/courses/$id': typeof AppCoursesIdRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/feed'
    | '/profile'
    | '/rep'
    | '/courses/$id'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/feed'
    | '/profile'
    | '/rep'
    | '/courses/$id'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/feed'
    | '/_app/profile'
    | '/_app/rep'
    | '/_app/courses/$id'
    | '/_app/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rep': {
      id: '/_app/rep'
      path: '/rep'
      fullPath: '/rep'
      preLoaderRoute: typeof AppRepRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/_app/courses/$id': {
      id: '/_app/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof AppCoursesIdRouteImport
      parentRoute: typeof AppCoursesRoute
    }
  }
}

interface AppCoursesRouteChildren {
  AppCoursesIdRoute: typeof AppCoursesIdRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesIdRoute: AppCoursesIdRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedRoute: typeof AppFeedRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRepRoute: typeof AppRepRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedRoute: AppFeedRoute,
  AppProfileRoute: AppProfileRoute,
  AppRepRoute: AppRepRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
